-- day 11 The 10 Business Questions You Must Answer
-- 1. What is the total revenue generated by the company?
select sum(sales) as total_revenue
from superstore_datasets;

-- 2. Which region generates the most sales?
select region, sum(sales) as region_sales
from superstore_datasets
group by Region
order by region_sales desc
limit 1;

-- 3. Which product category is most popular by number of orders?
select category, count(*) as category_orders
from superstore_datasets
group by category
order by category_orders desc limit 1;

-- Intermediate Level
-- 1.Which are the top 5 customers by total sales?
select `customer name`, sum(sales) as customer_sales
from superstore_datasets
group by `customer name`
order by customer_sales desc
limit 5;

-- 2.Which ship mode is used most often and does it vary by region?
select `ship mode`, region, count(*) as ship_moodeorders
from superstore_datasets
group by `ship mode`, region
order by ship_moodeorders desc ;

-- 3. Are there any orders where the company made a loss? (Sales below 300)
select count(*) as orders
from superstore_datasets
where sales < 300;

-- Advanced Level:
-- 1. Which sub-categories perform above their category average?
with sub_totals as ( select `Sub-Category`, category, SUM(Sales) AS total_sales from superstore_datasets GROUP BY Category, `Sub-Category`),
category_average as ( select category, avg(sales) as category_avg from superstore_datasets group by Category)
select st.`Sub-Category`, st.Category, st.total_sales, ca.category_avg
from sub_totals st join category_average ca on st.category = ca.category
where st.total_sales > ca.category_avg
ORDER BY st.Category, st.total_sales DESC;

-- 2.Who are the top 2 customers in each region by total sales?
with ranked as  (select `customer name`, region, sum(sales) as total_sales , rank() over (partition by region order by sum(sales) desc) as rnk
from superstore_datasets group by `customer name`, region)
select * from ranked
where rnk <= 2
;

-- 3.How does each state rank within its region by total sales?
select state, region, sum(sales) as total_sales, rank() over (partition by region order by sum(sales) desc) as ranks
from superstore_datasets
group by state, Region;

-- 4.For each category, show the running total of sales ordered by Row ID
select category, `row id`, sum(sales) over ( partition by category order by `row id`) as running_total
from superstore_datasets;

select * from superstore_datasets;